from sqlalchemy import Column, Integer, String, Float
from src.adapter.orm.base import Base

class Estabelecimento(Base):
    __tablename__ = 'estabelecimentos'
    cnpj_basico = Column(String, primary_key=True)
    cnpj_ordem = Column(String, primary_key=True)
    cnpj_dv = Column(String)
    identificador_matriz_filial = Column(Integer)
    nome_fantasia = Column(String)
    situacao_cadastral = Column(Integer)
    data_situacao_cadastral = Column(String)
    motivo_situacao_cadastral = Column(Integer)
    nome_cidade_exterior = Column(String)
    pais = Column(String)
    data_inicio_atividade = Column(String)
    cnae_fiscal_principal = Column(String)
    cnae_fiscal_secundaria = Column(String)
    tipo_logradouro = Column(String)
    logradouro = Column(String)
    numero = Column(String)
    complemento = Column(String)
    bairro = Column(String)
    cep = Column(String)
    uf = Column(String)
    municipio = Column(String)
    ddd_1 = Column(String)
    telefone_1 = Column(String)
    ddd_2 = Column(String)
    telefone_2 = Column(String)
    ddd_fax = Column(String)
    fax = Column(String)
    correio_eletronico = Column(String)
    situacao_especial = Column(String)
    data_situacao_especial = Column(String)
